apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-cafe-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/salamituns/wave-cafe'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 