apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-cafe
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-cafe
  template:
    metadata:
      labels:
        app: wave-cafe
    spec:
      containers:
      - name: wave-cafe
        image: REPLACE_ME_IMAGE
        ports:
        - containerPort: 80 