name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wave-cafe
      K8S_MANIFEST: k8s/deployment.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Update Kubernetes manifest image tag
        run: |
          ./scripts/update-manifest.sh ${{ env.K8S_MANIFEST }} ${{ env.IMAGE_NAME }} ${{ steps.vars.outputs.sha_short }}

      - name: Commit and push updated manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update k8s manifest with image ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
          branch: main
          file_pattern: ${{ env.K8S_MANIFEST }} 